# [build-system]
# requires = ["hatchling"]
# build-backend = "hatchling.build"

[project]
name = "leet75_quickhacks"
version = "0.0.0"
requires-python = ">= 3.12"

[tool.pytest.ini_options]
addopts = [
  "--import-mode=importlib",
]
